### PR TITLE
Case‐Sensitive File Systems

### LINKED ISSUE #14: Inoperable on Case Sensitive File Systems
Mint does not work on case sensitive file systems. Almost nothing from the read‐me can execute successfully. For example:

```shell
$ git clone https://github.com/yonaskolb/Mint
Cloning into 'Mint'...
remote: Counting objects: 179, done.
remote: Total 179 (delta 0), reused 0 (delta 0), pack-reused 179
Receiving objects: 100% (179/179), 29.98 KiB | 1023.00 KiB/s, done.
Resolving deltas: 100% (76/76), done.

$ cd Mint

$ swift run mint run realm/SwiftLint
Fetching https://github.com/nsomar/Guaka.git
...
Fetching https://github.com/oarrabi/StringScanner
Cloning https://github.com/nsomar/Guaka.git
Resolving https://github.com/nsomar/Guaka.git at 0.1.3
...
Cloning https://github.com/onevcat/Rainbow.git
Resolving https://github.com/onevcat/Rainbow.git at 2.1.0
error: no executable product named 'mint'
```

Even running “Mint” (capitalized) there are internal problems:

```swift
$ swift run Mint run realm/SwiftLint
Compile Swift Module 'ShellOut' (1 sources)
...
Compile Swift Module 'MintKit' (3 sources)
Compile Swift Module 'Mint' (1 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/Mint
🌱  Using latest tag "0.23.0"
🌱  Checking out https://github.com/realm/SwiftLint.git "0.23.0"...
🌱  Building swiftlint. This may take a few minutes...
🌱  Installing swiftlint...
🌱  Error: Couldn't find command swiftlint
```

(The folder `/usr/local/lib/mint/packages/github.com_realm_SwiftLint/build/0.23.0` is entirely empty.)

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
Fixes #14.

Actually, since there are no tests, it is hard to tell if I dealt with every possible casing issue, but I did fix everything that caught my eye, and I can now guarantee that Mint can successfully run...

```shell
$ mint run realm/SwiftLint
```

...which I imagine involves most operations Mint performs.

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -22,7 +22,7 @@ let package = Package(
         // Targets are the basic building blocks of a package. A target can define a module or a test suite.
         // Targets can depend on other targets in this package, and on products in packages which this package depends on.
         .target(
-            name: "Mint",
+            name: "mint",
```
Comment (yonaskolb) [inline Package.swift]: Instead of changing the target name to lowercase, I'd rather specify an explicit product with a lowercase name
```
.executable(name: "mint", targets: ["Mint"]),
```

File: README.md [hunk 2]
```diff
@@ -35,15 +35,15 @@ Make sure Xcode 9 is installed first.
...
+$ brew tap yonaskolb/Mint https://github.com/yonaskolb/Mint.git
 $ brew install mint
 ```
 
 ### Make
 
 ```sh
-$ git clone https://github.com/yonaskolb/mint.git
-$ cd mint
+$ git clone https://github.com/yonaskolb/Mint.git
```
Comment (yonaskolb) [inline README.md]: I could also change the repo name to be lowercase. What do you think? I think I prefer uppercase, but could be swayed

Comment (SDGGiesbrecht) [reply README.md]: There is no reason not to keep the repository and package names capitalized. That is the way most projects are and I think it looks nicer.

File: Package.swift (hunk 1 above)
Comment (SDGGiesbrecht) [reply Package.swift]: @yonaskolb, I will double check, but I am pretty sure that the `name` argument for products is only used in the manifests of other packages where they specify which of your products to actually use. I think it is the target name that defines the name of the executable file itself, and hence what you use from the shell.

If that is correct, then it would be reasonable to make the executable name uppercase if you want (for referencing in manifests), but **the target name needs to lowercase unless you want the command to always be used capitalized, i.e. `$ Mint install ...`**, which would be a little unusual.

**Comment by yonaskolb** [comment]
To fix the issue with SwiftLint from #14, you would need to remove the `lowercased()` here as well https://github.com/yonaskolb/Mint/blob/master/Sources/Mint/main.swift#L66
Otherwise it will look for command `swiftlint`

**Comment by SDGGiesbrecht** [comment]
> Otherwise it will look for command swiftlint

...which is correct in SwiftLint’s case, and for the lion’s share of other tools as well.

**Comment by yonaskolb** [comment]
Yeah, removing that lowercase will fix other libraries. I assumed SwiftLint was capital case because the error you posted in #14 said:
> Error: Couldn't find command swiftlint

File: Package.swift (hunk 1 above)
Comment (SDGGiesbrecht) [reply Package.swift]: Just tested it. My assumption was wrong. Holdover from Swift 3 I guess.

Comment (SDGGiesbrecht) [reply Package.swift]: I will fix it.

Comment (yonaskolb) [reply Package.swift]: Can you rename the `mint` folder back to `Mint` as well then

Comment (SDGGiesbrecht) [reply Package.swift]: Actually, it only sort of works. The executable file gets the product name, but when the executable file differs from the corresponding target name (which I imagine is rare) some of `swift package`’s subcommands start to have trouble. So I would still highly recommend using `mint` for both the target and product (if you want to start exposing it as a product).

Comment (yonaskolb) [reply Package.swift]: Interesting. What sort of subcommands have trouble?

**Comment by SDGGiesbrecht** [comment]
That error was because the `.build/Release/` folder did not exist to copy anything out of. (It is really `.build/release`.)

File: Package.swift (hunk 1 above)
Comment (SDGGiesbrecht) [reply Package.swift]: `describe`, `dump-package`, etc.

**Comment by SDGGiesbrecht** [comment]
@yonaskolb,

Summary of the decisions you need to make before I can do anything else.

(Case‐insensitive file systems will never notice the difference no matter what you decide.)

1. Which do you want users to do?
- `$ mint install ...`
- `$ Mint install ...`

2. How do you want to guess the executable’s name (at least until #17)?
- Fold to lowercase. (Fails for row 4.) 
- Identical to package name. (Fails for rows 2 and 3.)

For reference, here is the casing of the names of other Swift‐related tools, including all the tools in Mint’s read‐me:

<table>
  <tr>
    <th>Documentation</th>
    <th>Package</th>
    <th>Target</th>
    <th>Directory</th>
    <th>Product</th>
    <th>Command<br>(actual)</th>
    <th>Command<br>(read‐me)</th>
  </tr>
  <tr>
    <td colspan="1">Swift<br>Xcode<br>CocoaPods<br>Git<br>Homebrew<br>Jazzy<br>Slather<br>Swift Version Manager<br>Travis Client</td>
    <td colspan="4">∅</td>
    <td colspan="2">swift<br>xcodebuild<br>pod<br>git<br>brew<br>jazzy<br>slather<br>swiftenv<br>travis</td>
  </tr>
  <tr>
    <td colspan="2">Carthage<br><b>Mint (pr)</b><br>SourceKitten<br>SwiftLint<br>Workspace</td>
    <td colspan="5">carthage<br><b>mint</b><br>sourcekitten<br>swiftlint<br>workspace</td>
  </tr>
  <tr>
    <td colspan="6">Marathon<br><b>Mint (master)</b><br>XcodeGen</td>
    <td colspan="1">marathon†<br><b>mint</b>†<br>xcodegen†</td>
  </tr>
  <tr>
    <td colspan="2">danger-swift</td>
    <td colspan="2">Runner</td>
    <td colspan="3">danger-swift</td>
  </tr>
  <tr>
    <td colspan="7">SwagGen</td>
  </tr>
</table>

†Wherever “Command (actual)” does not match “Command (read‐me)”, the tool appears broken on case‐sensitive file systems, since all examples in the read‐me and documentation just result in `command not found`. (@JohnSundell, that includes Marathon, in case you are interested.)

**Comment by yonaskolb** [comment]
I would like the executable to be lowercase. If it's possible to still have the target name be capitalised in SPM that's great, otherwise it's ok to sacrifice that and also make it also lowercase.

In terms of parsing the executable name, we should just leave the value untouched instead of lowercasing it. If we don't find the command with the casing given, we should try using lowercase.
When #17 is complete, the value will be unused or as a last resort fallback

**Comment by SDGGiesbrecht** [comment]
The target name is capitalized again. It is an internal detail, so if problems arrive in the future, it will not be a breaking change to conform it to the executable name.

***

The executable name of a given tool is now presumed to be exactly the same as the package name.

It turns out trying fallback names (i.e. lowercase) would require a severe refactor, because right now [the `Package` must be initialized with an executable name before the repository is ever retrieved](https://github.com/yonaskolb/Mint/blob/d38055610f347aa8e784a0eb3f5889ca3a686ef9/Sources/MintKit/MintKit.swift#L64-L69). I therefore deem fallback guessing to be out of the scope of this pull request. For now, I instead fixed the examples in the read‐me to explicitly specify the executable name when it differs from the repository name (i.e. SwiftLint).

File: README.md [hunk 3]
```diff
@@ -96,11 +96,11 @@ These commands all have 1 or 2 arguments:
 
 #### Examples
 ```sh
-$ mint install yonaskolb/xcodegen@1.2.4 "xcodegen --spec spec.yml" # pass some arguments
-$ mint install yonaskolb/xcodegen@1.2.4 # use version 1.2.4
-$ mint install yonaskolb/xcodegen # use newest tag
-$ mint run yonaskolb/xcodegen@1.2.4 # run 1.2.4
-$ mint run xcodegen # use newest tag and find xcodegen in installed tools
+$ mint install yonaskolb/XcodeGen@1.2.4 "XcodeGen --spec spec.yml" # pass some arguments
```
Comment (yonaskolb) [inline README.md]: It reminds me to do the same lowercase product in XcodeGen 👍

File: README.md [hunk 4]
```diff
@@ -127,11 +127,11 @@ If this file is found in you repo, then all those directories will be copied int
...
-Just run `mint run` or `mint install` and the following:
+Just run `mint run` or `mint install` with the following:
 
-- [realm/SwiftLint](https://github.com/realm/SwiftLint)
-- [JohnSundell/Marathon](https://github.com/JohnSundell/Marathon)
-- [yonaskolb/XcodeGen](https://github.com/yonaskolb/XcodeGen)
-- [yonaskolb/SwagGen](https://github.com/yonaskolb/SwagGen)
+- $ mint run [realm/SwiftLint](https://github.com/realm/SwiftLint) swiftlint
+- $ mint run [JohnSundell/Marathon](https://github.com/JohnSundell/Marathon)
+- $ mint run [yonaskolb/XcodeGen](https://github.com/yonaskolb/XcodeGen)
```
Comment (yonaskolb) [inline README.md]: 👍
