### PR TITLE
Checkout fresh package each install

### LINKED ISSUE #12: Update does not work correctly with reused branches
In my project I reused a branch name (`mint`, for development).

So the local mint checkout folder already contained a `mint` branch from an earlier checkout and now origin contains a new `mint` branch, which is basically completely different from the local `mint` branch.

When running `git checkout <branch name>` in <https://github.com/yonaskolb/Mint/blob/master/Sources/MintKit/MintKit.swift#L124> through `$ mint update gnosis/bivrost-swift@mint` Mint just checkouts the local branch again, ignoring the new branch on origin, building the old version again. So basically using `update` forces it to rebuild, but not to actually update the version it builds.

Solutions:
- In my simple tests, just adding `origin/` to the branch name could work (not sure about tagged versions though). So the command then would be `git checkout origin/mint`, which checks out the latest origin branch.
- You could also clear the checkouts folder before fetching, which would have the same effect.

In addition, `update` fails [here](https://github.com/yonaskolb/Mint/blob/master/Sources/MintKit/MintKit.swift#L133) when the repo name is not the same as the command name, which might have a technical reason, but is counter intuitive because I only want to update the package, not actually run it.

Maybe adding a `Mintfile` could help with this, as it could identify how the executable is named. Or Mint could just copy all executables that are produced by SPM.

### LINKED ISSUE #18: Stop Keeping Tool Repositories Around
It is dangerous to keep a tool repositories around for reuse.

It is not just about saving space (though that is reason enough in and of itself).

In the event of a force push, even to an unrelated branch, several Git commands will suddenly begin to fail.

When a new version of Swift comes out and `swift build` creates new files (such as Swift 4 did with `Package.resolved`), it causes the repository to become dirty and causes problems with future attempts to check something out.

For reasons such as this it would be safer to clone, build, copy the product(s) and then remove the repository each time. (The products themselves are safe to cache for future use.)

### PR DESCRIPTION
**Pull request by yonaskolb**
Fixes #18 
Fixes #12

### CODE REVIEW

**Comment by yonaskolb** [comment]
@SDGGiesbrecht @zweigraf

File: Sources/MintKit/MintKit.swift [hunk 1]
```diff
@@ -91,21 +91,25 @@ public struct Mint {
...
 
-        if !package.checkoutPath.exists {
-            print("🌱  Cloning \(package.git)...")
-            do {
-                try shellOut(to: "git clone \(package.git) \(package.checkoutPath.lastComponent)", at: package.path.string)
-            } catch {
-                throw MintError.repoNotFound(package.git)
-            }
-        }
+        let checkoutPath = Path.temporary + "mint"
```
Comment (yonaskolb) [inline Sources/MintKit/MintKit.swift]: @SDGGiesbrecht I assume `NSTemporaryDirectory()` which is what `PathKit.temporary` uses is suitable on Linux?

Comment (SDGGiesbrecht) [reply Sources/MintKit/MintKit.swift]: @yonaskolb, Probably, but Linux does not work [at all](https://travis-ci.org/yonaskolb/Mint/jobs/306167062#L679), and would probably require swapping out dependencies, so I would not even worry about it.

Note: `NSTemporaryDirectory()` is on the road to deprecation as `Foundation` moves away from paths in favour of the `URL`‐based API. If that matters to you, you can take a peek [here](https://github.com/SDGGiesbrecht/SDGCornerstone/blob/223f17b34b8bcb44141b120a0c968a20ff8ca40f/Sources/SDGCornerstone/Persistence/FileManager.swift#L49).
